import { Prisma } from '@prisma/client';

export const medicineScheduleSelect = {
  id: true,
  prescriptionId: true,
  userId: true,
  medicineName: true,
  medicineForm: true,
  doseAmount: true,
  doseUnit: true,
  frequencyType: true,
  frequencyValue: true,
  timesPerDay: true,
  specificDays: true,
  specificDates: true,
  mealTiming: true,
  scheduledTimes: true,
  startDate: true,
  endDate: true,
  status: true,
  notes: true,
  sideEffects: true,
  refillReminder: true,
  refillAt: true,
  createdAt: true,
  updatedAt: true,
  completedAt: true,
  // Uncomment to include prescription info
  // prescription: { select: { id: true, title: true, doctorName: true } },
} satisfies Prisma.MedicineScheduleSelect;

export const medicineScheduleWithLogsSelect = {
  id: true,
  prescriptionId: true,
  userId: true,
  medicineName: true,
  medicineForm: true,
  doseAmount: true,
  doseUnit: true,
  frequencyType: true,
  frequencyValue: true,
  timesPerDay: true,
  specificDays: true,
  specificDates: true,
  mealTiming: true,
  scheduledTimes: true,
  startDate: true,
  endDate: true,
  status: true,
  notes: true,
  sideEffects: true,
  refillReminder: true,
  refillAt: true,
  createdAt: true,
  updatedAt: true,
  completedAt: true,
  doseLogs: {
    orderBy: { scheduledAt: 'desc' as const },
    take: 10,
    select: {
      id: true,
      scheduledAt: true,
      takenAt: true,
      status: true,
      skipReason: true,
      note: true,
    },
  },
} satisfies Prisma.MedicineScheduleSelect;
